<?php

namespace GS\UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByPostName($postName)
    {
        $qb = $this->createQueryBuilder('u')
          ->leftJoin('u.post', 'p')
          ->where('p.name LIKE :pattern')
          ->setParameter('pattern', $postName)
        ;

        return $qb
          ->getQuery()
          ->getResult()
        ;
    }

    public function findCurrentTreasurer()
    {
        $qb = $this->createQueryBuilder('u')
          ->leftJoin('u.post', 'p')
          ->where('p.name LIKE :pattern')
          ->setParameter('pattern', 'Trésorier')
        ;

        return $qb
          ->getQuery()
          ->getOneOrNullResult()
        ;
    }
}
