gs_stats:
    resource: "@GSStatsBundle/Resources/config/routing.yml"
    prefix:   /stats

gs_bill:
    resource: "@GSBillBundle/Resources/config/routing.yml"
    prefix:   /bill

gs_settings:
    resource: "@GSSettingsBundle/Resources/config/routing.yml"
    prefix:   /settings

gs_feedback:
    resource: "@GSFeedbackBundle/Resources/config/routing.yml"
    prefix:   /feedback

gs_mail:
    resource: "@GSMailBundle/Resources/config/routing.yml"
    prefix:   /

core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

gs_mailer:
    resource: "@GSMailerBundle/Resources/config/routing.yml"
    prefix:   /mailer

gs_platform:
    resource: "@GSPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform

# gs_user:
#     resource: "@GSUserBundle/Resources/config/routing.yml"
#     prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
