<?php

namespace GS\BillBundle\Repository;

/**
 * paymentMeansRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class paymentMeansRepository extends \Doctrine\ORM\EntityRepository
{
}
