version: '2'

services:
    db:
        image: mysql:8.0.0
        ports:
           - "${MYSQL_PORT}:3306"
        environment:
           MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
           MYSQL_USER: ${MYSQL_USER}
           MYSQL_PASSWORD: ${MYSQL_PASSWORD}
           MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
            - db-data:/var/lib/mysql:delegated

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db
        ports:
            - ${PMA_PORT}:80
    php:
        build:
            context: .
            dockerfile: ./php7-fpm/Dockerfile
            args:
                - TIMEZONE
                - SSH_ROOT_PASSWORD
        ports:
            - ${SSH_PORT}:22
        environment:
            - MYSQL_PORT
            - MYSQL_ROOT_PASSWORD
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_DATABASE
            - MAILER_TRANSPORT
            - MAILER_USER
            - MAILER_PASSWORD
            - MAILER_HOST
            - SECRET
    nginx:
        depends_on:
          - db
        build:
            context: nginx
            dockerfile: Dockerfile
        ports:
            - ${NGINX_PORT}:80
        links:
            - db

volumes:
    db-data:
        driver: local
