version: '2'

services:
    db:
        image: mysql:8.0.0
        ports:
           - "${MYSQL_PORT}:3306"
        environment:
           MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
           MYSQL_USER: ${MYSQL_USER}
           MYSQL_PASSWORD: ${MYSQL_PASSWORD}
           MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
            - db-data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db
        ports:
            - ${PMA_PORT}:80
    php:
        # build:
        #     context: php7-fpm
        build:
            context: .
            dockerfile: ./php7-fpm/Dockerfile
            args:
                - TIMEZONE
                - SSH_ROOT_PASSWORD
        ports:
            - ${SSH_PORT}:22
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
    nginx:
        depends_on:
          - db
        build: nginx
        ports:
            - ${NGINX_PORT}:80
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
        links:
            - db

volumes:
    db-data:
        driver: local
