<?php

namespace GS\FeedbackBundle\Repository;

/**
 * FbClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FbClientRepository extends \Doctrine\ORM\EntityRepository
{
}
