gs_stats_main:
    path:     /
    defaults:
        _controller: GSStatsBundle:Interface:main

gs_stats_analysis:
    path:     /analysis
    defaults:
        _controller: GSStatsBundle:Interface:analysis
