services:
#    gs_stats.example:
#        class: GS\StatsBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

   gs_stats.repository:
       class: GS\StatsBundle\Service\StatsService
       arguments:
           - "@doctrine.orm.entity_manager"
