<?php

namespace GS\FeedbackBundle\Repository;

/**
 * FbClient_DenialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FbClient_DenialRepository extends \Doctrine\ORM\EntityRepository
{
}
