<?php

namespace GS\FeedbackBundle\Repository;

/**
 * FbStudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FbStudentRepository extends \Doctrine\ORM\EntityRepository
{
}
