<?php

namespace GS\FeedbackBundle\Repository;

/**
 * QuestionModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionModelRepository extends \Doctrine\ORM\EntityRepository
{
}
