<?php

namespace GS\BillBundle\Repository;

/**
 * BillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUnpaid()
    {
        $qb = $this->createQueryBuilder('bill')
          ->leftJoin('bill.billState', 'bs')
          ->where("bs.name LIKE :pattern")
          ->setParameter('pattern', 'Émise')
        ;

        return $qb
          ->getQuery()
          ->getResult()
        ;
    }
}
