<?php

namespace GS\BillBundle\Repository;

/**
 * billStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class billStateRepository extends \Doctrine\ORM\EntityRepository
{
}
