<?php

namespace GS\BillBundle\Repository;

/**
 * BillMailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillMailRepository extends \Doctrine\ORM\EntityRepository
{
}
