<?php

namespace GS\MailerBundle\Repository;

/**
 * GenderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenderRepository extends \Doctrine\ORM\EntityRepository
{
}
