<?php

namespace GS\MailerBundle\Repository;

/**
 * ProspeMailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProspeMailRepository extends \Doctrine\ORM\EntityRepository
{
}
