<?php

namespace GS\MailerBundle\Repository;

/**
 * SpecializationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecializationRepository extends \Doctrine\ORM\EntityRepository
{
}
