<?php

namespace GS\MailerBundle\Repository;

/**
 * StateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StateRepository extends \Doctrine\ORM\EntityRepository
{
    public function getStateIndex()
    {
        $qb = $this->createQueryBuilder('s');

        $result = $qb->getQuery()->getResult();

        $stateIndex = array();

        for ($i=0; $i < count($result); $i++) {
            $stateIndex[$result[$i]->getName()] = $result[$i]->getId();
        }

        return $stateIndex;
    }

}
